# Generated by Django 5.0.4 on 2024-06-24 22:51

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gw2_items',
            old_name='venter_value',
            new_name='vender_value',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='gw2_items',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_salvage_records',
            name='record_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
